### PR TITLE
replace icon_home with icon_earth

### PR DESCRIPTION
**Pull request by ildar**
to get rid of Circled_dot totally.
The reason behind this is this symbol of Sun is massively occult, see https://en.wikipedia.org/wiki/Circled_dot

### CODE REVIEW

**Comment by scoute-dich** [comment]
I've not the same opinion like you concerning the icon. But anyway, I removed it.

**Comment by ildar** [comment]
Thank you! 👍

**Comment by ildar** [comment]
with newest version I see one screenshot in Help needs recapturing..
Thanks again!

**Comment by scoute-dich** [comment]
Done.

**Pull request closed without merging**
