### PR TITLE
Added some database.close() for Favicon Database

### PR DESCRIPTION
**Pull request by woheller69**
I saw some error messages in the logcat, so I fixed it.

But, somewhere there is obviously also a close statement missing for the Ninja4.db:

2021-07-13 16:09:17.965 11063-11078/de.baumann.browser W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/de.baumann.browser/databases/Ninja4.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
2021-07-13 16:09:17.965 11063-11078/de.baumann.browser W/System: A resource failed to call close. 
2021-07-13 16:09:17.965 11063-11078/de.baumann.browser W/System: A resource failed to call close. 

Unfortunately I have not found it...

### CODE REVIEW

**Comment by woheller69** [comment]
And now there are also messages for pass_DB_v01.db

A SQLiteConnection object for database '/data/user/0/de.baumann.browser/databases/pass_DB_v01.db' was leaked!
A resource failed to call close. 
Is pass_DB_V01.db still needed? Seems like an old database for bookmarks (?)

**Comment by scoute-dich** [comment]
> Is pass_DB_V01.db still needed?
No. I will also look at it. Thank you again for your great work.

**Comment by scoute-dich** [comment]
Should we remove the favicons on history and start tab? Because it looks a bit confusing with only favicons for domains, when a bookmark is saved?

Or move to the end of the list item?

**Comment by scoute-dich** [comment]
I removed pass_DB_V01.db and all usages.

**Comment by scoute-dich** [comment]
I just saw that at the starttab favicons are also displayed. I added them also in history tab,

**Comment by scoute-dich** [comment]
I just pushed it to master. I think I should release an update this week?

**Comment by woheller69** [comment]
If you store them also for all entries in history, the database will grow and grow, as they are never deleted. But I think other browsers do this as well and the images are not big.

Regarding Start Site entries I could imagine to store them in future as bookmark with color 0 (which I think is unused).
Then we would also have the time property available, where settings for Javascript, desktop mode, etc are stored and could be edited like in bookmarks.

A new release is a good idea.

I am just testing some Javascripts (copied from Firefox plugins) which avoid canvas fingerprinting, WebGL fingerprinting, etc
Works quite nice :-)  They are under Mozilla Public License 2.0. So I think we could use them with the right license statements

**Comment by woheller69** [comment]
For a new release don't forget to add a file to changelogs in fastlane

**Comment by woheller69** [comment]
regarding database errors. I think all methods accessing the database need to be "synchronized" methods.

       public sychronized ...

Otherwise a new open can come before close

**Pull request merged**
