### PR TITLE
Do not add lines starting with "#" to hosts

### PR DESCRIPTION
**Pull request by woheller69**
I don`t think we need to load lines starting with "#".
This reduces hosts by a few thousand lines.
I did not remove it at download time, so the downloaded file still has the comments, e.g. one could read and display the date of the file if needed.

### CODE REVIEW

**Comment by woheller69** [comment]
Is there a reason why you were using this host list? Unified hosts = (adware + malware)
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

There are several more lists. The list with all entries is this one with 113,901 instead of 80,474 entries:
Unified hosts + fakenews + gambling + porn + social
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

**Comment by woheller69** [comment]
When a new tab is opened the new tab started in mobile mode but the icon showed dekstop mode.
Now a new tab still opens in mobile mode but the icon will read the desktopMode from webview and adapt accordingly.

**Comment by woheller69** [comment]
I also added a line with the date of the hosts file in the settings menu.
I noticed that some preference keys are string resources, e.g. @string/sp_ad_block.
Is there a reason for that? The key is not visible to the user, only title or summary. 
I had to change it to sp_ad_block, otherwise I get crashes...

**Comment by woheller69** [comment]
what do you think about adding a property desktopMode to each entry in startpage, bookmarks, and history?
When an item is opened from there we could apply the desired mode automatically. If you are interested in that feature I could try to implement it.

**Comment by scoute-dich** [comment]
> https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
I changed it.

> I noticed that some preference keys are string resources, e.g. @string/sp_ad_block.
Is there a reason for that? The key is not visible to the user, only title or summary.
No, there is no reason. For several years, this project started as a fork of the no longer maintained Ninja Browser. This is still "old" code.

> I also added a line with the date of the hosts file in the settings menu.
**_Displaying the date works, but it gets not updated._** I changed the update interval to once a day, as you suggested with the first pull request.

> what do you think about adding a property desktopMode to each entry in startpage, bookmarks, and history?
I think this could be a good idea. But when adding it on the list-context-menu, it should be also added in the context-menu-link.

**_Thanks again for the work._**

**Comment by woheller69** [comment]
Host file date shows the date from within the file, not the download date. So one week should work as well.
You will only see a change if the source has been updated.

**Comment by scoute-dich** [comment]
> what do you think about adding a property desktopMode to each entry in startpage, bookmarks, and history?

This is implemented with the latest commit.

**Comment by woheller69** [comment]
I don't think, that is what I meant. I wanted to save for each bookmark whether it shall be opened in desktop or mobile mode. So when you open a site from bookmarks, the mode will be as it was when you stored the bookmark.

**Comment by scoute-dich** [comment]
I understand. I think storing this within the bookmark can not be done without changing the database. When I made  this last time, a lot of things got broken. So I do not want to touch the database again.

**Comment by woheller69** [comment]
yeah, I know. I have a database in my weather app, too. 
I think, I could handle it. But the solution with context menu in bookmarks is also good.

I removed these old strange string resources for preference keys to clean up code. Will come as new pull request.

**Pull request merged**
