### PR TITLE
Use ListSwitchPreference from org.woheller69.preferences

### PR DESCRIPTION
**Pull request by woheller69**
I created a new repository org.woheller69.preferences with switch preferences and created a new ListSwitchPreference.
This can be used to replace the CheckBoxPreference + ListPreference for start_tab

### CODE REVIEW

**Comment by woheller69** [comment]
On some pages, e.g. marketwatch.com managing cookies is not possible on some devices because the buttons are obstructed by the bottom app bar. Usually the bar disappears if you scroll the page a little. But they don´t let you scroll. Therefore if scrolly==0 a swipe to top now removes the app bar and gives access to the buttons

**Comment by woheller69** [comment]
The latest commit is for downloading DataURIs #577
It works well on my Android 11 tablet. On my Android 6.0.1 and Android 10 it fails with storage permission problems for the
Downloads folder. Maybe you have an idea how to fix this.

Can e.g. be tested here:
https://dopiaza.org/tools/datauri/examples/index.php
https://igv.org/web/release/current/examples/dataURI.html

**Comment by woheller69** [comment]
Now it also works on Android 6.0.1 and 10.
There was a problem in hasPermissionStorage. 
For Android 6 to 10 it always returned false, no matter if permission was granted or not.

Now, if the permission has not been granted before the first download will fail and the permission will be requested.
Next time - if the permission is there - it works.

**Comment by scoute-dich** [comment]
Hi,
I just reverted "Use ListSwitchPreference from org.woheller69.preferences", since I do not want third party libraries in my project.

**Comment by woheller69** [comment]
No problem. We can also copy it into the project

**Pull request merged**
