### PR TITLE
Add save bookmark icon to overflow menu

### PR DESCRIPTION
**Pull request by woheller69**

### CODE REVIEW

**Comment by scoute-dich** [comment]
Hi,

I just removed the icon, to display a settings icon. To make UI consistent I also added this in the fast toggle dialog. There were some users who didn't find the settings activity.

You can assign a gesture to save bookmarks of you need it often.

I think this is the better solution for the average user.

**Comment by woheller69** [comment]
ok, I will use a gesture.

I just came across Global Privacy Control. Have you thought about adding the Sec-GPC header like DNT for http requests?

**Comment by scoute-dich** [comment]
No have not heard of that since now.

**Comment by woheller69** [comment]
https://www.theregister.com/2020/10/10/global_privacy_control/

**Pull request merged**
