### PR TITLE
Remember javascript setting when browsing within same domain

### PR DESCRIPTION
**Pull request by woheller69**
When deactivating javascript for the domain (with general javascript setting on) and you open a new link within the same domain the javascript setting was activated every time you open a new link.

Now when a link within the same domain is opened the javascript setting will not be modified. 
You can modify it once and then browse within the domain

### CODE REVIEW

**Comment by scoute-dich** [comment]
You are the best! I'll merge and test. Thanks.

**Comment by woheller69** [comment]
we could think about storing this in bit5 of time for a bookmark, like the desktop mode setting in bit 4

**Comment by scoute-dich** [comment]
That's not necessary, since you can whitelist the the domain.

I just copied the method for the remote content.

**Comment by woheller69** [comment]
If you want Javascript active in general but block it for a few domains the whitelist will not help...

**Comment by scoute-dich** [comment]
That's right. I didn't consider that. If you want, you can do that and make a pull request. But we could not make the same thing with the remote content, or can we add a 5th bit? As said, that are things, that I do not know.

**Comment by woheller69** [comment]
I will have a look at it. We have many many bits left...

**Pull request merged**
