### PR TITLE
Custom error pages

### PR DESCRIPTION
**Pull request by Bnyro**
Instead of showing the default WebView error page (only containing an Android icon and the message) which doesn't fit the app's theme, the app now displays custom error pages instead. 
Those error pages follow the theme colors by the app and also allow the user to try reloading the page with one click.

Screenshots can be found below:
error-my
error-system

### CODE REVIEW

**Comment by scoute-dich** [comment]
Thanks a lot for your hard work! ;-)

**Comment by Bnyro** [comment]
You're welcome, already waiting for the new update patiently ;)

**Comment by scoute-dich** [comment]
Due to privacy concerning, I'll remove “Clipboard record as search suggestion”.

I also changed the condition, when to show the error page. If you want, you can test it. I'll release an update this week, since work starts again next week. :-(

**Comment by Bnyro** [comment]
> Due to privacy concerning, I'll remove “Clipboard record as search suggestion”.
> 
Can't we just turn it into an option that is disabled by default instead?

**Comment by scoute-dich** [comment]
I do not want too many settings (there are already too many). If you copy an url (or any text) to clipboard, you can share it directly to FOSS Browser on newer Android versions. FOSS Browser can also receive shred any text from any application, so I do not see the benefits.

**Comment by Bnyro** [comment]
I don't think adding a few more options will be an issue as long as they're well structured. For example, the custom header and search engine preferences should most likely become moved to a separate tab.
Apart from that the Twitter and Instagram redirects can now be removed in favor of the custom redirects feature.

**Comment by scoute-dich** [comment]
So my vacations are already over. I will test the new features tomorrow and then release the update on Sunday. Then, for the next weeks I do not have much time.

If you have time, can try to implement your suggestions and make a pull request. If you do so, please try to use existing strings, since it's a haste to update all translations, when there are new ones. Also, do not worry, when you hear nothing from my side for a time.

Thanks again for your help.

**Comment by Bnyro** [comment]
I might do a PR for that in the coming weeks if I find time and motivation for it, but I'm okay with keeping it without the clipboard suggestions for now since pasting the url is not much more of an effort than having it as a suggestion.
Are there any other translations that need to be done except German and the main English strings? If yes, you should consider using Weblate for translations (which is free for Foss projects).

**Pull request merged**
