### PR TITLE
Fix problem for downloading DataUri on Android11

### PR DESCRIPTION
**Pull request by woheller69**
I tested the latest version again. Now on Android 11 I can export my bookmarks. Downloading DataURIs did not work anymore.
With the changes of this commit it works again, but only if permissions have already been granted previously.
I do not how how to request permissions from HelperUnit because I would need someActivityResultLauncher.
requestPermission(context,activity,Fragment_settings_Backup.someActivityResultLauncher); is not allowed
(Non-static field 'someActivityResultLauncher' cannot be referenced from a static context)...

On Android 10 exporting bookmarks does not work. It opens a popup and tells me that FOSS Browser needs Permission...
If I click "OK" nothing happens. At next click the popup will open again and again.

But it works if we increase         android:maxSdkVersion="29" instead of "28" (not included in this commit).
Then I have to first revoke the permission in phone settings, then it will be requested again and works.
Also for DataURIs.

Probably the hasPermissionStorage method has to replaced by checkPermission throughout the whole app, right?

### CODE REVIEW

**Comment by scoute-dich** [comment]
Thanks. Can you please test it again? I had to solve some problems, while merging your pull-request.

**Comment by woheller69** [comment]
ok, will try

**Comment by woheller69** [comment]
Tested again. Works on Android 11 and 6.0.1. On Android 10 it does NOT work. I only works if android:maxSdkVersion is set 29 instead of 28 in AndroidManifest.
For Downloads in all cases it only works if storage permission has been requested before e.g. by exporting bookmarks. 
Then I can also download a DataUri. So it would be good to have to option to call requestPermission also from BrowserUnit and HelperUnit. Problem is the "someActivityResultLauncher" which is needed...

There are 2 more places where hasPermissionStorage is used (download and saveAs). This should probably also be replaced by checkPermissionStorage.

**Comment by woheller69** [comment]
just to be clear: I am talking about the maxSdkVersion of the permission for writing to storage. The limit could be removed completely in my view because requestPermission already handles the different Android versions

**Comment by scoute-dich** [comment]
> Why do we need someActivityResultLauncher?

That is something I had from the official docs to implement scoped storage. I changed it to `context.startActivity(intent);`.

**Pull request merged**
