### PR TITLE
Allow to reopen last tab

### PR DESCRIPTION
**Pull request by Tobiplayer3**
I've added a settings option to open a new tab whenever the last tab is closed instead of exiting the app.

### CODE REVIEW

**Comment by scoute-dich** [comment]
What is the intention of this behavior? Because when I really trigger this setting, how will it be possible to close the app? Eveytime you close, a new tab will appear. I'm thinking of removing it. If you don't want to close the browser, you can do everything (search, enter urls, open overview) from this last tab. And of you don't want to leave the browser accidentally, just check the option of thy he confirmation dialog before leaving FOSS Browser.

**Comment by Tobiplayer3** [comment]
In my opinion it's annoying to have a dialog that just warns you about closing the last tab. Sometimes I just want to clean up my browser tabs and closing the browser or getting this dialog is an unnecessary additional step. Of coure you could argue that it's not that useful but for me it just feels better. Feel free to remove or change it but for some people it might be useful.

**Comment by scoute-dich** [comment]
At the moment this works only, when closing in the tab preview. If this intended, we can change the settings strings to "open new tab ... In the overview". Since the default value is "false" this would be also ok for me.

**Comment by Tobiplayer3** [comment]
It should also work when you open the menu on the bottom right corner and press "Close tab" as well as when you bind any gesture to close the tab. But yes, it's mainly for the overview and it may be good idea to change some settings strings.

**Comment by scoute-dich** [comment]
It works now also, when pressing the back button. So this will be implemented in next update. Thanks for your contribution.

**Pull request merged**
