### PR TITLE
Improvement for Desktop View and correct icon colors when importing bookmarks

### PR DESCRIPTION
**Pull request by woheller69**

### CODE REVIEW

**Comment by scoute-dich** [comment]
Hi,

**_thanks again for your help._**

I moved the desktop mode in the "Others menu" together with the new entry for switching day/night mode. It is now also reachable in the "FastSettings" dialog, with an own icon.

The "saving as bookmark" feature I'll not implement. I do not want more buttons on the toolbar. Especially on small devices, that would be too much, if you still want space for the website title.

**Comment by woheller69** [comment]
ok, desktop mode via FastSetting sounds good.
What about adding the save as bookmark icon to the left of the reload button? That would be a click less...

**Comment by woheller69** [comment]
PS: I saw you stopped developing your own weather app. Maybe you want to try my RadarWeather ..
https://f-droid.org/de/packages/org.woheller69.weather/

**Comment by scoute-dich** [comment]
> What about adding the save as bookmark icon to the left of the reload button? That would be a click less...

Yes, that sounds good. Also, we do not need new strings, what I like because of missing translations. Feel free to open a new pull request!

**Pull request merged**
