### PR TITLE
Added button for quick bookmarking and possibility to switch between desktop view and mobile view

### PR DESCRIPTION
**Pull request by woheller69**
Hope you like it

### CODE REVIEW

**Comment by woheller69** [comment]
Found a problem on a device with large display. Will try to fix and then create a new pull request

**Comment by woheller69** [comment]
Bug should be fixed now

**Comment by scoute-dich** [comment]
I just pushed code to Github. Now the pull request can not be merged. Can you please update your code?

**Comment by woheller69** [comment]
Should work now

**Comment by scoute-dich** [comment]
I'll look at it. Thank you! It's a often asked feature, but until now I didn't found a way to implement desktop view without bugs.

**Pull request merged**
