### PR TITLE
Browser_right integration + startup recognition of request desktop state

### PR DESCRIPTION
**Pull request by futrDevelopment**
Title. thinking about either continuing with the tab-ish direction the Right_browser went in to extrapolate that into a set of 5 tabs (who really needs more than that? I mean its android) or just this really nice tab resource that will take some time to implement but would be nice if it worked.  Nvm, these changes solidify the adblock and request desktop upgrades so they are necessary, and should be in the base.

### CODE REVIEW

**Comment by scoute-dich** [comment]
What tab resource?

**Comment by futrDevelopment** [comment]
Actually, I'm looking at a few of them and haven't made up my mind yet.
The Browser_right was meant to be a demo of how to expand on that and turn
that into several tabs, and looking at the way the right browser works, it
seems likethat would work just fine.  I'm going to take a look at the
Browser_right this week and see if I can continue in that direction
otherwise the outside tab solutions (all git-hub tab stuff, easily
searchable) I'd have to sort of plug into the browser like I did with the
adblock.  Pls don't forget to add that adblock page to your resources
because that was the solution I used for the adblock, even though his was
dependent on using his webview which was inferior to yours.

**Comment by futrDevelopment** [comment]
omg I just found a glitch in this pull request, hold off for a while I
think I need to rework the optimization I just tested it on another phone
and it keeps refreshing :( ill resubmit another pull when Ive got it right.

**Comment by futrDevelopment** [comment]
OMG dude I just got 5 tabs working in my version just by extrapolating the functionality in the toolbar() function to cycle thru 5 tabs :)  I thought I was gonna have to do more glueing and pasting from open sources but everything I needed was right there in Browser the whole time.  If you want my 5 tab solution let me know, it does change the names of Browser_left and Browser right and changes it to a set of five tab classes tab1 thru tab5.

**Comment by scoute-dich** [comment]
You're really great man! I would be very happy if you show me your solution. Many people, and I also, would like more tabs. But I really couldn't find a solution on my on. As said before, I didn't Kern learn developing in a professional way...

Regards
Gaukler Faun

**Comment by futrDevelopment** [comment]
ok but I'm like 23 pull commits behind you and I'm pretty sure that means I have to update from your main branch and i'm 100 percent sure I have no idea how to do that...

**Comment by futrDevelopment** [comment]
either way, I just got back from work and I'm gonna put in the tabs and hopefully it works but it seems like my pull request is not being integrated,  I really don't have the foggiest clue what I'm doing right now.

**Comment by futrDevelopment** [comment]
I think I'll wait, I've got some optimizations to make in the version I have which is, like I said before, greatly reduced.  I'm thinking theres probably some sort of thing I messed up because I'm seeing a "this branch has conflicts that must be resolved" error.  any Idea what that is?

**Comment by scoute-dich** [comment]
"This branch has conflicts that must be resolved" means that I have done changes that are not compatible with your changes. But that's no problem. If your repo is up to date I will look at your commits and take them over to my repo by copy and paste.

Anyway thanks for your help.

I also want to implement the browser activities as fragments... But I think that's a lot of work... But I think I will try it...

**Comment by futrDevelopment** [comment]
K but don't merge this yet I still need to put the color tab identification system in so the user knows what tab he's on and also integrate that into what used to be the popup asking in right or left browser. I work all day so I wasn't able to put it in last night but I'm off in an hour, shouldn't take more than an hour after that.

**Comment by futrDevelopment** [comment]
Mhm then life called and said you'll prob be late lil got a few things to wrap up then i wrap up the browser contribution pls a little patience it was mothers day weekend and I had to make my mom smile big bbl

**Comment by futrDevelopment** [comment]
Aaaaand done.  sry, life got ahold of me and I got delayed again.  Take a look at it now, but before you do i'd like to sort of go over my rationale for using this method of presenting the tabs to the user.

1)First and most important reason is, practically speaking, you are out of room on your toolbar for anything other than whats there already.

2)Secondly, that shouldn't be a problem because this browser starts out being a much different sort of browser anyway, so not everything has to be done the conventional way to say the least.  As a matter of fact, it is better to continue moving in the direction of originality since Browser is already heavily different by design.

So, I looked at the fact that browser uses color changing as one of its sort of visual indicators to the user already, with the transition from browsing to the lists.  So why not incorporate that same theme into the tab functionality that way the user gets the tabs they want and Browser delivers them in a way no other browser does, just like with the lists and the ergonomic controls.  

The key to integrating the color choosing though was the long press menu in my opinion.  The user can open anything in any tab they choose by longclicking the link and selecting from the menu.  Its a fast way to populate all five of your tabs and tapping the toolbar to cycle through them is extremely fast and efficient, and the color changes are pleasing and different than any other browser.  

So browser gets its tabs and becomes even more unique in one shot.

Let me know what you think of it and especially if you found a bug or whatever, something I overlooked or should add.

**Comment by scoute-dich** [comment]
Thanks a lot. I got your changes merged and tested it.

Meanwhile I changed the following things:

1. Changed app name to "Five", because of five tabs.
2. Changed the tab names and colors to the five continents btw. the Olympic colors.
3. Fixed an close app issue.

Next things I will do:

- open menu on toolbar click to switch faster between tabs.
- swept left and right on webview to switch to neighbour tab

And one more thing:

We all have job/school, family and other interests. So it's ok when we have no time for coding. You even mustn't help me. I'm also doing this in my free time, mainly for my personal effort. So don't matter when nothing happens here for a few days or EB even weeks...

Thanks one more time for your help. "Five" wouldn't be what it now is without you.

Greetings from sunny Germany
Gaukler Faun

**Comment by futrDevelopment** [comment]
Excellent, I had fun making the upgrades.  Best of luck with Five, I'm proud to have been a part of it :)

**Pull request closed without merging**
