### PR TITLE
Add try catch for Downloadmanager

### PR DESCRIPTION
**Pull request by woheller69**
Just had a crash when trying to download a Covid certificate from impfzenten.bayern.
It has a .bin extension but is a .pdf document.

Now it still does not download but at least the app does not crash

### CODE REVIEW

**Comment by scoute-dich** [comment]
I just released a new version (v8), because all main bugs are now solved. Thanks again for your work.

**Comment by woheller69** [comment]
Great. I am very happy with the browser now. I used DuckDuckGo before, but there were some features missing, especially the AdBlocker.
2 things I would suggest to change in future:
1. make URL editable in bookmark editor
2. the new icon is nice, but I think, there is too much of the dark background. On a home screen with dark background the icon seems to be quite small

**Comment by woheller69** [comment]
Question about  sp_remote:

The description says: Enable remote content, which is not directly from the website you are visiting. 

But is this really true?
With that preference we are switching setDomStorageEnabled and this, as far as I understand allows the application to store page elements that could include user sensitive information. Setting the DOM Storage value to false will prevents local storage from being used. So it is not about "content" but about storage.

https://www.sevenforums.com/tutorials/106540-dom-storage-cookies-enable-disable.html
DOM Storage is often compared to HTTP cookies. Like cookies, Web developers can store per-session or domain-specific data as name/value pairs on the client using DOM Storage. However, unlike cookies, DOM Storage makes it easier to control how information stored by one browser window is visible to another.

In my view the description needs to be changed...

**Comment by scoute-dich** [comment]
I opened an issue for that, as reminder. I possibly make a break for a few days.

**Pull request merged**
