### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by BO41**
adds a CODE_OF_CONDUCT to the Community profile of this profile.
better have any then none at all. At least that's what I think

### CODE REVIEW

**Comment by BO41** [comment]
@scoute-dich I would also recommend creating a ["how to contribute"](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file. But I am not good at writing and I don't know what you want to have in there.

maybe @HarryHeights  is good at writing something like this as well

**Comment by HarryHeights** [comment]
I'm good at pretty much writing everything if essential information is given. 
@scoute-dich hasn't given me feedback on my proposal to create a FAQs and Privacy Policy document though. I don't think he might be needing this too.

**Comment by BO41** [comment]
@HarryHeights nice, sounds promising.
Just give @scoute-dich some time :)

**Comment by HarryHeights** [comment]
Definitely. I guess he's into a lot of programming at the moment.

**Comment by scoute-dich** [comment]
No, I'm going on vacation tomorrow. So the next two weeks I won't code anything... :wink:

**Comment by HarryHeights** [comment]
Hahaha... Can I come along with you please? How long are we gonna be staying?

**Comment by HarrySystems** [comment]
It would be great to have a "how to contribute" file. I would really like to help with improvements but I'm having trouble understanding how to setup and build the Android project...

**Pull request merged**
