### PR TITLE
Add favicons to bookmarks and start site entries

### PR DESCRIPTION
**Pull request by woheller69**
I played around with favicons, which are received by the webchromeclient anyway.
I added a new database where favicons are saved if the site is stored as bookmark or start site entry.
Existing bookmarks will be updated next time you open the site. It may take a few seconds until the favicon is available after loading the site.

Let me know if you like it. It may need some more fine tuning

### CODE REVIEW

**Comment by woheller69** [comment]
This opens new possibilities, e.g. start site in future could have a grid layout and show icons. Just as an idea.

**Comment by woheller69** [comment]
with type for distinguishing between records it would also be possible to store the desktop mode, javascript,... settings for star site entries

**Comment by scoute-dich** [comment]
I manually merged the last two commits. At the moment I'm afraid of merging the favicons, since you said, that there are some problems. I do not have time and knowledge to solve them.

**Comment by woheller69** [comment]
No, there are no problems with the favicons, they work great.
I just meant that if we have the favicons there might be other changes (fine tuning) as well. E.g. show them also on the search result or other things. I also thought about adding the additional database to backup/restore. But I don´t think it is necessary, as it rebuilds automatically as you browse.

**Comment by scoute-dich** [comment]
Can you please sync with master, there conflicts. Then I'll merge it. Thanks in advance.

**Comment by scoute-dich** [comment]
I managed it.

**Pull request merged**
