### PR TITLE
Make code better readable by

### PR DESCRIPTION
**Pull request by woheller69**
adding isDesktopMode, isJavascript, isDomStorage, iconColor to Record.
Move bit operations for these parameters to database classes.

Instead of      
                 
     ninjaWebView.setJavaScript(!((time&32) ==32));

we e.g. now have

     ninjaWebView.setJavaScript(record.getJavascript());

No functional change

### CODE REVIEW

**Comment by scoute-dich** [comment]
Thanks a lot for that. I think I can learn a lot from that commit.

**Comment by woheller69** [comment]
We could think about saving desktopmode, javascript,... also for history entries.
At the moment we are not doing this and opening an entry from history will use default settings which may be different from the settings when the page was called.
We could use e.g. the lower 8bit of time, which would reduce time accuracy by 256 milliseconds, and save the status the same way (in the same bits) as for bookmarks or start site entries.

A problem would only arise for existing entries in history which already use these bits. What do you think?

**Comment by scoute-dich** [comment]
That is a good idea.

But as I said: I do not know how this "bit-stuff" works. As I want to learn, can you give me link to a tutorial (preferably in German), where I can start?

**Comment by woheller69** [comment]
If you like this feature I can implement it. 

If you search for Java and bitwise operators you will find some tutorials. 
I would e.g. use the (~255)&time to blank out the lower 8bits of time

**Pull request merged**
