### PR TITLE
Some more improvements

### PR DESCRIPTION
**Pull request by woheller69**
Scroll to top of bookmarks when opening bookmarks

Show colored bookmark icon when editing bookmark category

Use settings stored in bookmark when a bookmark is found in search

### CODE REVIEW

**Comment by woheller69** [comment]
I think next version is 8.0, at least :-)

**Comment by scoute-dich** [comment]
And again: Thanks a lot.

> Scroll to top of bookmarks when opening bookmarks

I will not merge. One of my design principles is having all controls at the bottom, if possible. So all lists in the overview are stacked from bottom.

**Comment by woheller69** [comment]
But then the alphabetical order should be reversed 

A the bottom Z at the top

**Comment by scoute-dich** [comment]
Yes but how. That's a thing I tried since weeks...

**Comment by woheller69** [comment]
But maybe it is a misunderstanding. The list is still stacked from the bottom. But if you have 50 bookmarks and the screen is full you would not see your top bookmark anymore.

**Comment by woheller69** [comment]
Collections.reverse(list)

see PR

**Pull request merged**
