### PR TITLE
Edit filter names / Privacy Enhancement

### PR DESCRIPTION
**Pull request by woheller69**
I found a nice class for a preference with switch and text which I modified in order to use it for editing the filter names
Screenshot_20210721-110814

I added a new chip which activates measures against Browser Fingerprinting:
- Block WebRTC requests which can reveal local IP address
- Prevent Canvas fingerprinting
- Prevent WebGL fingerprinting
- Prevent Audiocontext fingerprinting
- Prevent Font fingerprinting
- Spoof screen resolution, color depth, device memory, hardwareConcurrency, 
- Remove info about battery, network connection, keyboard, media devices info, 
- Prevent sendBeacon and ping

(scripts for canvas, webgl, audiocontext, font fingerprinting are taken from Firefox plugins which are published under
Mozilla V2.0 license. I contacted the author and he sent me an email that he agrees to use these scripts unter GPL V3)

### CODE REVIEW

**Comment by woheller69** [comment]
Default for the fingerprinting stuff is off, so the user must activate it via the chip

**Comment by scoute-dich** [comment]
Thanks. I'll test it. First look seems pretty good. ;-)

**Comment by woheller69** [comment]
I would also like to use the switch_text preference for user agent. Have it already working. But unfortunately the text size for app:titleText
does not match the size of the other preferences, it is a little bigger and I cannot change it.
I hate this layout stuff...
If you have an idea, let me know.

**Comment by scoute-dich** [comment]
At the moment I'm working on the fasttoggle layout stuff. I'll merge your other pull request and order the other layout stuff. Perhaps that's something I can do better. ;-)

**Comment by woheller69** [comment]
Good to hear that you are good at layouts. My last version works well, with and without icon, with and without title, with and without summary,...
Font size also fits, but for sure it can be improved.
Changing font size for title only worked by changing font size of switch and edittext at the same time...

**Pull request merged**
